package com.intellij.bigdatatools.databricks.toolwindow.config

import com.intellij.bigdatatools.databricks.model.ServerRunInfo
import com.intellij.bigdatatools.databricks.model.WorkflowRunInfo
import com.intellij.ide.util.PropertiesComponent
import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.openapi.components.service
import com.intellij.util.xmlb.XmlSerializerUtil
import com.jetbrains.bigdatatools.common.connection.updater.IntervalUpdateSettings
import com.jetbrains.bigdatatools.common.settings.ColumnVisibilitySettings

@State(name = "DatabricksSettings", storages = [Storage("databricks.xml")])
class DatabricksToolWindowSettings : PersistentStateComponent<DatabricksToolWindowSettings>, IntervalUpdateSettings {
  override var selectedConnectionId: String? = null

  private var serverRunTableColumns = mutableListOf(
    ServerRunInfo::startTime.name,
    ServerRunInfo::status.name,
  )
  val serverRunTableColumnSettings = ColumnVisibilitySettings(serverRunTableColumns)

  private var jobRunsTableColumns = mutableListOf(
    WorkflowRunInfo::startTime.name,
    WorkflowRunInfo::status.name,
    WorkflowRunInfo::duration.name,
  )
  val jobRunsColumnSettings = ColumnVisibilitySettings(jobRunsTableColumns)

  var lastShownToolWindowVersion: String? = null
    get() {
      return if (field != null) field
      else PropertiesComponent.getInstance().getValue(LAST_SHOWN_TOOLWINDOW_VERSION_KEY)
    }

  var skipStartServerConfirmation = false
  var skipStopServerConfirmation = false
  var skipRestartServerConfirmation = false

  var showAutogeneratedCellInResults = false
  var showCodeInResults = true

  override var configs: MutableMap<String, DatabricksClusterConfig> = mutableMapOf()

  override var dataUpdateIntervalMillis: Int = 30000

  override fun getState(): DatabricksToolWindowSettings = this

  override fun loadState(state: DatabricksToolWindowSettings) {
    XmlSerializerUtil.copyBean(state, this)
  }

  companion object {
    fun getInstance(): DatabricksToolWindowSettings = service()

    private const val LAST_SHOWN_TOOLWINDOW_VERSION_KEY = "databricks.toolwindow.lastShownVersion"
  }
}