# Copyright 2000-2026 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
platformVersion=263.4732.31
platformJavaVersion=25
pluginSinceBuild=263
pluginVersion=263.0.0

kotlin.stdlib.default.dependency=false

# Gradle performance settings
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
