package com.intellij.lang.puppet.psi;

import com.intellij.openapi.util.text.StringUtil;
import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;

import static com.intellij.lang.puppet.psi.PuppetDataTypes.CLASS_TYPE_NAME;
import static com.intellij.lang.puppet.psi.PuppetDataTypes.RESOURCE_TYPE_NAME;
import static com.intellij.lang.puppet.psi.PuppetDataTypes.TYPE_TYPE_NAME;

public interface PuppetDataType extends PuppetCompositePsiElement, PuppetTypeHolder {
  @NonNls String LOWERCASE_RESOURCE_TYPE_NAME = StringUtil.toLowerCase(RESOURCE_TYPE_NAME);
  @NonNls String LOWERCASE_CLASS_TYPE_NAME = StringUtil.toLowerCase(CLASS_TYPE_NAME);
  @NonNls String LOWERCASE_TYPE_TYPE_NAME = StringUtil.toLowerCase(TYPE_TYPE_NAME);

  /**
   * @return qualifying type of datatype
   */
  @Nullable
  String getQualifyingTypeName();

  /**
   * Method, generated by Grammar-Kit
   *
   * @return parameters block
   */
  @Nullable
  PsiPuppetDataTypeParametersBlock getDataTypeParametersBlock();

  /**
   * @return list of composite type parameters elements or null if there is no parameters block. For empty block returns empty list
   */
  @Nullable
  List<PsiElement> getParametersList();

  /**
   * @return a classname if this is a Class[...] data type and classname may be resolved, null otherwise
   */
  @Nullable
  String getEffectiveClassName();

  /**
   * Guesses parameter type by it's position (and probably other properties).
   *
   * @param parameterElement parameter element
   * @return Type or null if it's not possible to guess
   */
  @Nullable
  PuppetDataTypeParameterInfo getParameterInfo(@NotNull PsiElement parameterElement);

  /**
   * Returns parameter by zero-based index
   *
   * @param parameterIndex zero-based index
   * @return parameter psi element or null if can't find it
   */
  @Nullable
  PsiElement getParameterElement(int parameterIndex);
}
