package com.intellij.lang.puppet.psi;

import com.intellij.lang.puppet.psi.stubs.PuppetNodeDefinitionStub;
import org.jetbrains.annotations.Nullable;

public interface PuppetNodeDefinition extends PuppetStubBasedPolyNamedPsiElement<PuppetNodeDefinitionStub>,
                                              PuppetNamedScopeHolder,
                                              PupppetTopScopeHolder,
                                              PuppetPolyNamedPsiElement {

  /**
   * Generated by Grammar-Kit
   *
   * @return wrapper for nameholders of the node
   */
  @Nullable
  PsiPuppetNodeNamesList getNodeNamesList();
}
