package com.intellij.gwt.run.remoteUi;

import com.intellij.execution.filters.TextConsoleBuilderFactory;
import com.intellij.execution.ui.ConsoleView;
import com.intellij.openapi.Disposable;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.openapi.util.Disposer;
import com.intellij.openapi.util.NlsSafe;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

public class ModuleLogComponent implements Disposable {
  private final JPanel myMainPanel;
  private final ComboBox myModuleCombobox;
  private final JPanel myConsolePanel;
  private final Map<String, ConsoleView> myConsoleViews = new HashMap<>();
  private String myLastSelectedModule;
  private final Project myProject;

  public ModuleLogComponent(Project project) {
    myProject = project;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new BorderLayout(0, 0));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 3, new Insets(5, 5, 5, 5), -1, -1));
      myMainPanel.add(panel1, BorderLayout.NORTH);
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/GwtBundle", "label.module"));
      panel1.add(label1,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myModuleCombobox = new ComboBox();
      panel1.add(myModuleCombobox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                       null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      panel1.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myConsolePanel = new JPanel();
      myConsolePanel.setLayout(new CardLayout(0, 0));
      myMainPanel.add(myConsolePanel, BorderLayout.CENTER);
    }
    myModuleCombobox.setMinimumAndPreferredWidth(300);
    myModuleCombobox.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        updateConsole();
      }
    });
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void updateConsole() {
    String module = (String)myModuleCombobox.getSelectedItem();
    if (module == null || module.equals(myLastSelectedModule)) return;

    ((CardLayout)myConsolePanel.getLayout()).show(myConsolePanel, module);
    myConsolePanel.revalidate();
    myConsolePanel.repaint();
    myLastSelectedModule = module;
  }

  public ConsoleView getOrCreateModuleConsole(@NotNull @NlsSafe String moduleName) {
    ConsoleView view = myConsoleViews.get(moduleName);
    if (view == null) {
      view = TextConsoleBuilderFactory.getInstance().createBuilder(myProject).getConsole();
      myConsoleViews.put(moduleName, view);
      myModuleCombobox.addItem(moduleName);
      myConsolePanel.add(moduleName, view.getComponent());
      if (myModuleCombobox.getItemCount() == 1) {
        myModuleCombobox.setSelectedIndex(0);
      }
    }
    return view;
  }

  public JPanel getMainPanel() {
    return myMainPanel;
  }

  @Override
  public void dispose() {
    for (ConsoleView view : myConsoleViews.values()) {
      Disposer.dispose(view);
    }
  }
}
