package com.intellij.gwt.make.report;

import com.intellij.gwt.GwtBundle;
import com.intellij.gwt.build.GwtBuildTargetScopeProvider;
import com.intellij.gwt.facet.GwtFacet;
import com.intellij.gwt.icons.GwtIcons;
import com.intellij.gwt.module.model.GwtModule;
import com.intellij.ide.BrowserUtil;
import com.intellij.ide.nls.NlsMessages;
import com.intellij.ide.util.PropertiesComponent;
import com.intellij.openapi.compiler.CompileContext;
import com.intellij.openapi.compiler.CompileScope;
import com.intellij.openapi.compiler.CompileStatusNotification;
import com.intellij.openapi.compiler.CompilerManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.ui.dsl.listCellRenderer.LcrJavaHelper;
import com.intellij.ui.dsl.listCellRenderer.RendererPresentation;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.lang.reflect.Method;
import java.util.List;
import java.util.ResourceBundle;

public class GenerateCompilerReportDialog extends DialogWrapper {
  private final JPanel myMainPanel;
  private final JComboBox<GwtModule> myModuleComboBox;
  private final JLabel myInfoLabel;
  private final Project myProject;
  private static final @NonNls String REPORT_FILE_PATH = "soycReport/compile-report/index.html";
  private final ViewReportAction myViewReportAction;
  private final CompileReportsHistory myReportsHistory;
  public static final @NonNls String MODULE_PROPERTY_KEY = "GWT.GenerateCompileReport.Module";

  public GenerateCompilerReportDialog(@NotNull Project project, final List<GwtModule> modules) {
    super(project);
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
      myModuleComboBox = new JComboBox();
      myMainPanel.add(myModuleComboBox, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                            GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                            null, null, 1, false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/GwtBundle", "label.gwt.module"));
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myInfoLabel = new JLabel();
      myInfoLabel.setText(" ");
      myMainPanel.add(myInfoLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                       GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null,
                                                       0, false));
      label1.setLabelFor(myModuleComboBox);
    }
    myReportsHistory = CompileReportsHistory.getInstance(project);
    myProject = project;
    setTitle(GwtBundle.message("dialog.title.generate.gwt.compile.report"));
    myViewReportAction = new ViewReportAction();
    final DefaultComboBoxModel model = new DefaultComboBoxModel();
    final String selectedModuleName = PropertiesComponent.getInstance(project).getValue(MODULE_PROPERTY_KEY);
    GwtModule toSelect = null;
    for (GwtModule gwtModule : modules) {
      model.addElement(gwtModule);
      if (selectedModuleName != null && selectedModuleName.equals(gwtModule.getQualifiedName())) {
        toSelect = gwtModule;
      }
    }

    myModuleComboBox.setModel(model);
    myModuleComboBox.setRenderer(LcrJavaHelper.create(
      "",
      value -> new RendererPresentation(GwtIcons.GoogleSmall, value.getQualifiedName())
    ));
    myModuleComboBox.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        updateView();
      }
    });
    if (toSelect != null) {
      myModuleComboBox.setSelectedItem(toSelect);
    }
    else {
      myModuleComboBox.setSelectedItem(0);
    }
    setOKButtonText(GwtBundle.message("button.text.generate"));
    init();
    updateView();
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private @Nullable CompileReportSource getSelectedSource() {
    final GwtModule module = (GwtModule)myModuleComboBox.getSelectedItem();
    if (module == null) return null;
    final GwtFacet facet = GwtFacet.getInstance(module);
    return facet != null ? new CompileReportSource(facet, module) : null;
  }

  @Override
  protected Action @NotNull [] createActions() {
    return new Action[]{getCancelAction()};
  }

  @Override
  protected Action @NotNull [] createLeftSideActions() {
    return new Action[]{getOKAction(), myViewReportAction};
  }

  @Override
  protected void dispose() {
    final CompileReportSource source = getSelectedSource();
    if (source != null) {
      PropertiesComponent.getInstance(myProject).setValue(MODULE_PROPERTY_KEY, source.getGwtModule().getQualifiedName());
    }
    super.dispose();
  }

  private void updateView() {
    final CompileReportSource source = getSelectedSource();
    setOKActionEnabled(source != null);
    myViewReportAction.setEnabled(source != null);
    if (source == null) {
      myInfoLabel.setText(" ");
      return;
    }

    CompileReportsHistory.GwtModuleCompileReport report = myReportsHistory.getCompileReport(source.getGwtModule().getQualifiedName());
    if (report == null || !getResultsFile(report).exists()) {
      myViewReportAction.setEnabled(false);
      myInfoLabel.setText(" ");
      return;
    }

    final long delta = System.currentTimeMillis() - report.getGenerationTime();
    myInfoLabel.setText(GwtBundle.message("label.text.compile.report.was.generated.0.ago", NlsMessages.formatDurationApproximate(delta)));
  }

  @Override
  protected void doOKAction() {
    final CompileReportSource source = getSelectedSource();
    if (source != null) {
      final CompilerManager manager = CompilerManager.getInstance(myProject);
      final CompileScope scope = manager.createModuleCompileScope(source.getFacet().getModule(), true);
      GwtBuildTargetScopeProvider.setGenerateCompileReportOption(scope, source);
      CompilerManager.getInstance(myProject).make(scope, new CompileStatusNotification() {
        @Override
        public void finished(boolean aborted, int errors, int warnings, @NotNull CompileContext compileContext) {
          if (!aborted && errors == 0) {
            openCompileReport(source);
          }
        }
      });
    }
    super.doOKAction();
  }

  private void openCompileReport(CompileReportSource source) {
    CompileReportsHistory.GwtModuleCompileReport report = myReportsHistory.getCompileReport(source.getGwtModule().getQualifiedName());
    if (report != null) {
      final File indexFilePath = getResultsFile(report);
      if (indexFilePath.exists()) {
        BrowserUtil.browse(indexFilePath.toURI());
      }
    }
  }

  private static File getResultsFile(CompileReportsHistory.GwtModuleCompileReport report) {
    final File root = new File(report.getPath());
    return new File(root.getAbsolutePath(), FileUtil.toSystemDependentName(REPORT_FILE_PATH));
  }

  @Override
  protected JComponent createCenterPanel() {
    return myMainPanel;
  }

  private class ViewReportAction extends DialogWrapperAction {
    ViewReportAction() {
      super(GwtBundle.message("action.ViewReportAction.text"));
    }

    @Override
    protected void doAction(ActionEvent e) {
      final CompileReportSource source = getSelectedSource();
      if (source != null) {
        openCompileReport(source);
        close(OK_EXIT_CODE);
      }
    }
  }
}
