package com.intellij.bigdatatools.zeppelin.notebook.interpreter

object ZeppelinDefaultMarkers {
  val markers = mapOf("" to "scala",
                      "spark" to "scala",
                      "sql" to "sql",
                      "dep" to "scala",
                      "pyspark" to "python",
                      "ipyspark" to "python",
                      "r" to "r",
                      "spark.spark" to "scala",
                      "spark.sql" to "sql",
                      "spark.dep" to "scala",
                      "spark.pyspark" to "python",
                      "spark.ipyspark" to "python",
                      "spark.r" to "r",
                      "md.md" to "markdown",
                      "sh.sh" to "sh",
                      "livy.spark" to "scala",
                      "livy.sql" to "sql",
                      "livy.pyspark" to "python",
                      "livy.pyspark3" to "python",
                      "livy.sparkr" to "r",
                      "flink.flink" to "scala",
                      "python.python" to "python",
                      "python.ipython" to "python",
                      "python.sql" to "sql",
                      "python.conda" to "sh",
                      "python.docker" to "sh",
                      "kylin.kylin" to "sql",
                      "jdbc.sql" to "sql",
                      "bigquery.sql" to "sql",
                      "pig.script" to "pig",
                      "pig.query" to "pig",
                      "md" to "markdown",
                      "sh" to "sh",
                      "livy" to "scala",
                      "flink" to "scala",
                      "python" to "python",
                      "kylin" to "sql",
                      "jdbc" to "sql",
                      "bigquery" to "sql",
                      "pig" to "pig")
}