package com.jetbrains.hadoop.monitoring.rest.resourcemanager.dao

data class CapacitySchedulerLeafQueueInfo(
  var numActiveApplications: Int = 0,
  var numPendingApplications: Int = 0,
  var numContainers: Int = 0,
  var maxApplications: Int = 0,
  var maxApplicationsPerUser: Int = 0,
  var userLimit: Int = 0,
  var users: UsersInfo? = null,
  var userLimitFactor: Double = 0.0,
  var AMResourceLimit: ResourceInfo? = null,
  var usedAMResource: ResourceInfo? = null,
  var userAMResourceLimit: ResourceInfo? = null,
  var preemptionDisabled: Boolean = false,
  var intraQueuePreemptionDisabled: Boolean = false,
  var defaultNodeLabelExpression: String? = null,
  var defaultPriority: Int = 0,
  var isAutoCreatedLeafQueue: Boolean = false,

  var capacity: Double = 0.0,
  var usedCapacity: Double = 0.0,
  var maxCapacity: Double = 0.0,
  var absoluteCapacity: Double = 0.0,
  var absoluteMaxCapacity: Double = 0.0,
  var absoluteUsedCapacity: Double = 0.0,
  var numApplications: Long = 0,
  var queueName: String? = null,
  var state: QueueState? = null,
  var queues: CapacitySchedulerQueueInfoList? = null,
  var resourcesUsed: ResourceInfo? = null,
  var hideReservationQueues: Boolean = false,
  var nodeLabels: List<String> = emptyList(),
  var allocatedContainers: Long = 0,
  var reservedContainers: Long = 0,
  var pendingContainers: Long = 0,
  var capacities: QueueCapacitiesInfo? = null,
  var resources: ResourcesInfo? = null,
  var minEffectiveCapacity: ResourceInfo? = null,
  var maxEffectiveCapacity: ResourceInfo? = null
)