platformVersion=263.4732.28
platformJavaVersion=25
pluginSinceBuild=263
pluginVersion=263.0.0

bigDataToolsCoreVersion=263.4732.28
bigDataToolsCoreUiVersion=263.4732.7
bigDataToolsAwsBaseVersion=263.4732.41
bigDataToolsAzureVersion=263.4732.41
bigDataToolsGoogleCloudVersion=263.4732.41
remoteFileSystemsVersion=263.4732.28

kotlin.stdlib.default.dependency=false

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g
