platformVersion=263.4732.28
platformJavaVersion=25
pluginSinceBuild=263
pluginVersion=263.0.0

bigDataToolsCoreVersion=263.4732.28
bigDataToolsCoreUiVersion=263.4732.7
bigDataToolsAwsBaseVersion=263.4732.41
bigDataToolsAzureVersion=263.4732.41
bigDataToolsGoogleCloudVersion=263.4732.41
remoteFileSystemsVersion=263.4732.28
pythonVersion=263.4732.28
scalaVersion=2026.3.4
completionMlRankingVersion=263.4732.7
jupyterVersion=263.4732.7
notebooksVersion=263.4732.7
databricksSdkVersion=0.104.0
nvWebsocketClientVersion=2.9
diffMatchPatchVersion=1.2

kotlin.stdlib.default.dependency=false

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g
