// Copyright 2000-2026 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package com.dbschema

import java.sql.Blob
import java.sql.CallableStatement
import java.sql.Clob
import java.sql.Connection
import java.sql.DatabaseMetaData
import java.sql.NClob
import java.sql.PreparedStatement
import java.sql.SQLException
import java.sql.SQLFeatureNotSupportedException
import java.sql.SQLWarning
import java.sql.SQLXML
import java.sql.Savepoint
import java.sql.Statement
import java.sql.Struct
import java.util.Properties
import java.util.concurrent.Executor

class ZeppelinSparkConnection internal constructor(private val driver: ZeppelinSparkJdbcDriver) : Connection {
  private var isClosed = false
  private var isReadOnly = true

  override fun getCatalog(): String = "default"

  override fun <T> unwrap(iface: Class<T>): T? = null

  override fun isWrapperFor(iface: Class<*>?): Boolean = false

  override fun createStatement(): Statement = MockStatement("")

  override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement =
    throw SQLFeatureNotSupportedException()

  override fun createStatement(
    resultSetType: Int,
    resultSetConcurrency: Int,
    resultSetHoldability: Int
  ): Statement = MockStatement("")

  override fun prepareStatement(sql: String): PreparedStatement = MockStatement(sql)

  override fun prepareCall(sql: String): CallableStatement = MockStatement(sql)

  override fun nativeSQL(sql: String): String =
    throw SQLFeatureNotSupportedException()

  override fun setAutoCommit(autoCommit: Boolean) {}

  override fun getAutoCommit(): Boolean = true

  override fun commit() {}

  override fun rollback() {}

  override fun close() {
    isClosed = true
  }

  override fun isClosed(): Boolean = isClosed

  override fun getMetaData(): DatabaseMetaData = ZeppelinSparkMetaData(this, driver)

  override fun setReadOnly(readOnly: Boolean) {
    isReadOnly = readOnly
  }

  override fun isReadOnly(): Boolean = isReadOnly

  override fun setCatalog(catalog: String) {}

  override fun setTransactionIsolation(level: Int) {}

  override fun getTransactionIsolation(): Int = Connection.TRANSACTION_NONE

  override fun getWarnings(): SQLWarning? = null

  override fun clearWarnings() {}

  override fun prepareStatement(
    sql: String, resultSetType: Int,
    resultSetConcurrency: Int
  ): PreparedStatement = throw SQLFeatureNotSupportedException()

  override fun prepareCall(
    sql: String,
    resultSetType: Int,
    resultSetConcurrency: Int
  ): CallableStatement = throw SQLFeatureNotSupportedException()

  override fun getTypeMap(): Map<String, Class<*>> = throw SQLFeatureNotSupportedException()

  override fun setTypeMap(map: Map<String?, Class<*>?>?): Unit = throw SQLFeatureNotSupportedException()

  override fun setHoldability(holdability: Int): Unit = throw SQLFeatureNotSupportedException()

  override fun getHoldability(): Int = throw SQLFeatureNotSupportedException()

  override fun setSavepoint(): Savepoint = throw SQLFeatureNotSupportedException()

  override fun setSavepoint(name: String): Savepoint = throw SQLFeatureNotSupportedException()

  override fun rollback(savepoint: Savepoint): Unit = throw SQLFeatureNotSupportedException()

  override fun releaseSavepoint(savepoint: Savepoint): Unit = throw SQLFeatureNotSupportedException()

  override fun prepareStatement(
    sql: String, resultSetType: Int, resultSetConcurrency: Int,
    resultSetHoldability: Int
  ): PreparedStatement = throw SQLFeatureNotSupportedException()

  override fun prepareCall(
    sql: String, resultSetType: Int, resultSetConcurrency: Int,
    resultSetHoldability: Int
  ): CallableStatement = throw SQLFeatureNotSupportedException()

  override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
    throw SQLFeatureNotSupportedException()

  override fun prepareStatement(
    sql: String,
    columnIndexes: IntArray
  ): PreparedStatement = throw SQLFeatureNotSupportedException()

  override fun prepareStatement(
    sql: String,
    columnNames: Array<String>
  ): PreparedStatement {
    throw SQLFeatureNotSupportedException()
  }

  override fun createClob(): Clob = throw SQLFeatureNotSupportedException()

  override fun createBlob(): Blob = throw SQLFeatureNotSupportedException()

  override fun createNClob(): NClob? = null

  override fun createSQLXML(): SQLXML? = null

  override fun isValid(timeout: Int): Boolean = true

  override fun setClientInfo(name: String, value: String) {}

  override fun setClientInfo(properties: Properties) {}

  override fun getClientInfo(name: String): String = name

  override fun getClientInfo(): Properties = Properties()

  override fun createArrayOf(typeName: String, elements: Array<Any>): java.sql.Array? = null

  override fun createStruct(typeName: String, attributes: Array<Any>): Struct? = null

  override fun setSchema(schema: String) {
    catalog = schema
  }

  override fun getSchema(): String = catalog

  override fun abort(executor: Executor) {}

  override fun setNetworkTimeout(executor: Executor, milliseconds: Int) {}

  @Throws(SQLException::class)
  override fun getNetworkTimeout(): Int = 400
}