package com.intellij.gwt.actions;

import com.intellij.CommonBundle;
import com.intellij.gwt.GwtBundle;
import com.intellij.gwt.facet.GwtFacet;
import com.intellij.gwt.uiBinder.UiBinderUtil;
import com.intellij.ide.util.ClassFilter;
import com.intellij.ide.util.TreeClassChooser;
import com.intellij.ide.util.TreeClassChooserFactory;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.InputValidator;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.util.NlsContexts;
import com.intellij.openapi.util.Ref;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.psi.JavaPsiFacade;
import com.intellij.psi.PsiClass;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.ui.DocumentAdapter;
import com.intellij.ui.RecentsManager;
import com.intellij.ui.ReferenceEditorComboWithBrowseButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Method;
import java.util.List;
import java.util.ResourceBundle;

public class CreateGwtUiBinderDialog extends DialogWrapper {
  private static final @NonNls String[] DEFAULT_ROOT_ELEMENT_TYPES = {
    "com.google.gwt.user.client.ui.HTMLPanel",
    "com.google.gwt.dom.client.DivElement",
  };
  private final JPanel myMainPanel;
  private final JTextField myNameTextField;
  private final ReferenceEditorComboWithBrowseButton myRootElementTypeEditor;
  private final InputValidator myValidator;
  private final Project myProject;
  private final GwtFacet myFacet;
  private final Ref<? super String> myRootElementType;
  private static final @NonNls String RECENT_ROOT_ELEMENT_KEY = "GwtCreateUiBinderDialog.RecentRootElementType";

  public CreateGwtUiBinderDialog(final Project project,
                                 GwtFacet facet,
                                 @NlsContexts.DialogTitle String dialogTitle,
                                 InputValidator validator,
                                 Ref<? super String> rootElementType) {
    super(project);
    myProject = project;
    myFacet = facet;
    myRootElementType = rootElementType;
    {
      final ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          final TreeClassChooserFactory factory = TreeClassChooserFactory.getInstance(myProject);
          final GlobalSearchScope scope = GlobalSearchScope.moduleWithDependenciesAndLibrariesScope(myFacet.getModule());
          final PsiClass elementClass = JavaPsiFacade.getInstance(myProject).findClass(UiBinderUtil.ELEMENT_BASE_CLASS, scope);
          final PsiClass widgetBaseClass = JavaPsiFacade.getInstance(myProject).findClass(UiBinderUtil.WIDGET_BASE_CLASS, scope);
          final TreeClassChooser chooser =
            factory.createNoInnerClassesScopeChooser(GwtBundle.message("dialog.title.select.type.of.root.element"), scope,
                                                     new RootElementClassFilter(elementClass, widgetBaseClass), null);
          chooser.showDialog();
          final PsiClass psiClass = chooser.getSelected();
          if (psiClass != null) {
            myRootElementTypeEditor.setText(psiClass.getQualifiedName());
          }
        }
      };
      myRootElementTypeEditor = new ReferenceEditorComboWithBrowseButton(listener, "", myProject, true, RECENT_ROOT_ELEMENT_KEY);
      for (String elementType : DEFAULT_ROOT_ELEMENT_TYPES) {
        myRootElementTypeEditor.prependItem(elementType);
      }
      final List<String> classes = RecentsManager.getInstance(myProject).getRecentEntries(RECENT_ROOT_ELEMENT_KEY);
      if (classes != null) {
        for (int i = classes.size() - 1; i >= 0; i--) {
          myRootElementTypeEditor.prependItem(classes.get(i));
        }
      }
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/GwtBundle",
                                                                       "label.text.enter.name.for.new.gwt.uibinder.class.and.ui.xml.file"));
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      myNameTextField = new JTextField();
      myMainPanel.add(myNameTextField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                           GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                           new Dimension(150, -1), null, 1, false));
      final JLabel label2 = new JLabel();
      this.$$$loadLabelText$$$(label2, this.$$$getMessageFromBundle$$$("messages/GwtBundle", "label.text.select.root.element.type"));
      myMainPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myMainPanel.add(myRootElementTypeEditor,
                      new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                          GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
      label1.setLabelFor(myNameTextField);
      label2.setLabelFor(myRootElementTypeEditor);
    }
    setTitle(dialogTitle);
    myValidator = validator;

    myNameTextField.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(@NotNull DocumentEvent e) {
        setOKActionEnabled(!StringUtil.isEmptyOrSpaces(myNameTextField.getText()));
      }
    });

    init();
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  @Override
  public JComponent getPreferredFocusedComponent() {
    return myNameTextField;
  }

  @Override
  protected void doOKAction() {
    final String name = myNameTextField.getText();
    final String rootElementType = myRootElementTypeEditor.getText().trim();
    if (StringUtil.isEmpty(rootElementType)) {
      Messages.showErrorDialog(myProject, GwtBundle.message("dialog.message.root.element.type.is.not.specified"),
                               CommonBundle.getErrorTitle());
      return;
    }

    RecentsManager.getInstance(myProject).registerRecentEntry(RECENT_ROOT_ELEMENT_KEY, rootElementType);
    myRootElementType.set(rootElementType);
    if (myValidator.checkInput(name) && myValidator.canClose(name)) {
      super.doOKAction();
    }
  }

  @Override
  protected JComponent createCenterPanel() {
    return myMainPanel;
  }

  private static class RootElementClassFilter implements ClassFilter {
    private final PsiClass[] myBaseClasses;

    RootElementClassFilter(PsiClass... baseClasses) {
      myBaseClasses = baseClasses;
    }

    @Override
    public boolean isAccepted(PsiClass aClass) {
      for (PsiClass baseClass : myBaseClasses) {
        if (baseClass == null || aClass.isInheritor(baseClass, true)) {
          return true;
        }
      }
      return false;
    }
  }
}
