package com.intellij.gwt.actions;

import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.InputValidator;
import com.intellij.openapi.util.NlsContexts;
import com.intellij.openapi.util.Ref;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.DocumentAdapter;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.NotNullFunction;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.text.Document;
import java.awt.Dimension;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

public class CreateGwtEventWithHandlerDialog extends DialogWrapper {
  private final JTextField myEventClassField;
  private final JTextField myHandlerClassField;
  private final JTextField myHandleMethodField;
  private final JPanel myMainPanel;
  private final InputValidator myValidator;
  private final Ref<? super String> myHandlerClassName;
  private final Ref<? super String> myHandleMethodName;

  public CreateGwtEventWithHandlerDialog(Project project,
                                         @NlsContexts.DialogTitle String dialogTitle,
                                         InputValidator validator,
                                         Ref<? super String> handlerClassName,
                                         Ref<? super String> handleMethodName) {
    super(project);
    myHandlerClassName = handlerClassName;
    myHandleMethodName = handleMethodName;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/GwtBundle", "label.text.event.class.name"));
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myEventClassField = new JTextField();
      myMainPanel.add(myEventClassField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                             GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                             new Dimension(150, -1), null, 1, false));
      final JLabel label2 = new JLabel();
      this.$$$loadLabelText$$$(label2, this.$$$getMessageFromBundle$$$("messages/GwtBundle", "label.text.handler.class.name"));
      myMainPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myHandlerClassField = new JTextField();
      myMainPanel.add(myHandlerClassField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                               GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                               new Dimension(150, -1), null, 1, false));
      final JLabel label3 = new JLabel();
      this.$$$loadLabelText$$$(label3, this.$$$getMessageFromBundle$$$("messages/GwtBundle", "label.text.event.handler.method.name"));
      myMainPanel.add(label3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myHandleMethodField = new JTextField();
      myMainPanel.add(myHandleMethodField, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                               GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                               new Dimension(150, -1), null, 1, false));
      label1.setLabelFor(myEventClassField);
      label2.setLabelFor(myHandlerClassField);
      label3.setLabelFor(myHandleMethodField);
    }
    setTitle(dialogTitle);
    myValidator = validator;

    myEventClassField.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(@NotNull DocumentEvent e) {
        setOKActionEnabled(!StringUtil.isEmptyOrSpaces(myEventClassField.getText()));
      }
    });
    setupSlaveField(myEventClassField, myHandlerClassField, dom -> dom + "Handler");
    setupSlaveField(myEventClassField, myHandleMethodField, dom -> "on" + StringUtil.trimEnd(dom, "Event"));
    init();
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  @Override
  protected void doOKAction() {
    final String name = myEventClassField.getText();
    myHandlerClassName.set(myHandlerClassField.getText());
    myHandleMethodName.set(myHandleMethodField.getText());
    if (myValidator.checkInput(name) && myValidator.canClose(name)) {
      super.doOKAction();
    }
  }

  @Override
  public JComponent getPreferredFocusedComponent() {
    return myEventClassField;
  }

  @Override
  protected JComponent createCenterPanel() {
    return myMainPanel;
  }

  private static void setupSlaveField(final JTextField master,
                                      final JTextField slave,
                                      @NonNls NotNullFunction<@NonNls String, @NonNls String> defaultValueProducer) {
    @NonNls String textChangedByUserKey = "TEXT_CHANGED_BY_USER";
    @NonNls String textIsChangingAutomatically = "TEXT_IS_CHANGING_AUTOMATICALLY";
    master.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(@NotNull DocumentEvent e) {
        final Document document = slave.getDocument();
        if (document.getProperty(textChangedByUserKey) != Boolean.TRUE) {
          document.putProperty(textIsChangingAutomatically, Boolean.TRUE);
          try {
            slave.setText(defaultValueProducer.fun(master.getText()));
          }
          finally {
            document.putProperty(textIsChangingAutomatically, null);
          }
        }
      }
    });
    slave.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(@NotNull DocumentEvent e) {
        final Document document = e.getDocument();
        if (document.getProperty(textIsChangingAutomatically) != Boolean.TRUE) {
          document.putProperty(textChangedByUserKey, Boolean.TRUE);
        }
      }
    });
  }
}
