package com.intellij.gwt.actions;

import com.intellij.gwt.facet.GwtFacet;
import com.intellij.javaee.web.WebRoot;
import com.intellij.javaee.web.facet.WebFacet;
import com.intellij.openapi.fileChooser.FileChooserDescriptor;
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.roots.ModuleRootManager;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.InputValidator;
import com.intellij.openapi.util.NlsContexts;
import com.intellij.openapi.util.NlsSafe;
import com.intellij.openapi.util.Ref;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.openapi.vfs.VfsUtilCore;
import com.intellij.psi.PsiDirectory;
import com.intellij.ui.ComboboxWithBrowseButton;
import com.intellij.ui.DocumentAdapter;
import com.intellij.ui.GuiUtils;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.jps.gwt.index.GwtModuleXmlConstants;

import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.text.JTextComponent;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Method;
import java.util.List;
import java.util.ResourceBundle;

public class CreateGwtModuleDialog extends DialogWrapper {
  private final JTextField myGwtModuleNameField;
  private final JCheckBox myCreateHtmlFileCheckBox;
  private final ComboboxWithBrowseButton myHtmlDirectoryPathField;
  private final InputValidator myValidator;
  private final PsiDirectory mySourceDirectory;
  private final Ref<? super String> myHtmlDirectoryRef;
  private boolean myAdjustingDirectory;
  private boolean myDirectoryWasChangedByHand;
  private final JComboBox myComboBox;
  private final JPanel myContentPanel;

  public CreateGwtModuleDialog(@NlsContexts.DialogTitle String dialogTitle,
                               GwtFacet facet,
                               InputValidator validator,
                               PsiDirectory sourceDirectory,
                               Ref<? super String> htmlDirectoryRef) {
    super(facet.getModule().getProject(), true);
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myContentPanel = new JPanel();
      myContentPanel.setLayout(new BorderLayout(0, 0));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
      myContentPanel.add(panel1, BorderLayout.CENTER);
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/GwtBundle", "new.module.dlg.prompt"));
      panel1.add(label1,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myGwtModuleNameField = new JTextField();
      panel1.add(myGwtModuleNameField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                           GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                           new Dimension(150, -1), null, 1, false));
      myCreateHtmlFileCheckBox = new JCheckBox();
      myCreateHtmlFileCheckBox.setSelected(true);
      this.$$$loadButtonText$$$(myCreateHtmlFileCheckBox,
                                this.$$$getMessageFromBundle$$$("messages/GwtBundle", "checkbox.create.html.and.css.files.in.directory"));
      panel1.add(myCreateHtmlFileCheckBox, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JPanel panel2 = new JPanel();
      panel2.setLayout(new BorderLayout(0, 0));
      myContentPanel.add(panel2, BorderLayout.SOUTH);
      panel2.setBorder(
        BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 15, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION,
                                         TitledBorder.DEFAULT_POSITION, null, null));
      myHtmlDirectoryPathField = new ComboboxWithBrowseButton();
      panel2.add(myHtmlDirectoryPathField, BorderLayout.CENTER);
      label1.setLabelFor(myGwtModuleNameField);
    }
    myComboBox = myHtmlDirectoryPathField.getComboBox();
    myValidator = validator;
    mySourceDirectory = sourceDirectory;
    myHtmlDirectoryRef = htmlDirectoryRef;
    setTitle(dialogTitle);
    setOKActionEnabled(false);
    myGwtModuleNameField.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(@NotNull DocumentEvent e) {
        setOKActionEnabled(!myGwtModuleNameField.getText().trim().isEmpty());
        adjustDirectory();
      }
    });
    myCreateHtmlFileCheckBox.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        GuiUtils.enableChildren(myCreateHtmlFileCheckBox.isSelected(), myHtmlDirectoryPathField);
      }
    });
    myComboBox.setEditable(true);
    ((JTextComponent)myComboBox.getEditor().getEditorComponent()).getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(@NotNull DocumentEvent e) {
        if (!myAdjustingDirectory) {
          myDirectoryWasChangedByHand = true;
        }
      }
    });

    myAdjustingDirectory = true;
    final WebFacet webFacet = facet.getWebFacet();
    if (webFacet != null) {
      for (WebRoot webRoot : webFacet.getWebRoots()) {
        myComboBox.addItem(FileUtil.toSystemDependentName(VfsUtilCore.urlToPath(webRoot.getDirectoryUrl())));
      }
    }
    myComboBox.addItem(computeHtmlDirectoryInSourcesPath());
    myComboBox.setSelectedIndex(0);
    myAdjustingDirectory = false;

    final FileChooserDescriptor descriptor = FileChooserDescriptorFactory.createSingleFolderDescriptor();
    descriptor.setRoots(ModuleRootManager.getInstance(facet.getModule()).getContentRoots());
    myHtmlDirectoryPathField.addBrowseFolderListener(facet.getModule().getProject(), descriptor);
    init();
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myContentPanel; }

  private @NlsSafe String computeHtmlDirectoryInSourcesPath() {
    final List<String> names = StringUtil.split(myGwtModuleNameField.getText(), ".");
    final PsiDirectory directory = names.size() > 1 ? CreateGwtModuleAction.getRootDirectory(mySourceDirectory) : mySourceDirectory;
    final StringBuilder path = new StringBuilder(directory.getVirtualFile().getPath());
    for (int i = 0; i < names.size() - 1; i++) {
      String name = names.get(i);
      if (!name.isEmpty()) {
        if (!path.isEmpty() && path.charAt(path.length() - 1) != '/') {
          path.append('/');
        }
        path.append(StringUtil.decapitalize(name));
      }
    }
    path.append("/").append(GwtModuleXmlConstants.DEFAULT_PUBLIC_PATH);
    return FileUtil.toSystemDependentName(path.toString());
  }

  @Override
  public JComponent getPreferredFocusedComponent() {
    return myGwtModuleNameField;
  }

  private void adjustDirectory() {
    if (myDirectoryWasChangedByHand) return;
    myAdjustingDirectory = true;
    try {
      final int lastItemIndex = myComboBox.getItemCount() - 1;
      boolean isLastItemSelected = myComboBox.getSelectedItem().equals(myComboBox.getItemAt(lastItemIndex));
      final String newPath = computeHtmlDirectoryInSourcesPath();
      if (isLastItemSelected) {
        myComboBox.getEditor().setItem(newPath);
      }
      myComboBox.removeItemAt(lastItemIndex);
      myComboBox.addItem(newPath);
    }
    finally {
      myAdjustingDirectory = false;
    }
  }

  @Override
  protected JComponent createNorthPanel() {
    return myContentPanel;
  }

  @Override
  protected JComponent createCenterPanel() {
    return null;
  }

  @Override
  protected void doOKAction() {
    final String moduleName = myGwtModuleNameField.getText().trim();
    myHtmlDirectoryRef.set(getHtmlDirectory());
    if (myValidator.checkInput(moduleName) && myValidator.canClose(moduleName)) {
      close(OK_EXIT_CODE);
    }
    else {
      close(CANCEL_EXIT_CODE);
    }
  }

  private @Nullable String getHtmlDirectory() {
    if (myCreateHtmlFileCheckBox.isSelected()) {
      return FileUtil.toSystemIndependentName((String)myComboBox.getSelectedItem());
    }
    return null;
  }
}
